version: '2.4'
services:
  procon1:
    container_name: procon1
    build:
      context: .
    image: prophet731/procon:develop
    restart: unless-stopped
    ports:
      - "27260:27260"
    volumes:
      - type: volume
        source: config1
        target: /opt/procon/Configs
      - type: volume
        source: plugin1
        target: /opt/procon/Plugins
      - type: volume
        source: log1
        target: /opt/procon/Logs
    security_opt:
      - no-new-privileges
    tty: true
    mem_limit: 3G
    mem_reservation: 2500M

volumes:
  config1:
  plugin1:
  log1:
