version: '2.4'
services:
  procon:
    container_name: ${INSTANCE_NAME}
    build:
      context: .
    image: prophet731/procon:develop
    restart: on-failure
    ports:
      - ${LAYER_PORT}:27260
    volumes:
      - type: bind
        source: ${CONFIG_PATH}
        target: /opt/procon/Configs
      - type: bind
        source: ${PLUGINS_PATH}
        target: /opt/procon/Plugins
      - type: bind
        source: ${LOGS_PATH}
        target: /opt/procon/Logs
    security_opt:
      - no-new-privileges
    tty: true
    mem_limit: 3G
    mem_reservation: 2500M
volumes:
  config1:
  plugin1:
  log1:
